export const alpha3_alpha2: { [key: string]: string } = {
  ARG: "AR",
  AUS: "AU",
  AUT: "AT",
  AZE: "AZ",
  BRN: "BH",
  BEL: "BE",
  BRA: "BR",
  CAN: "CA",
  CHL: "CL",
  CHN: "CN",
  COL: "CO",
  CZE: "CZ",
  DEN: "DK",
  FIN: "FI",
  FRA: "FR",
  GER: "DE",
  HUN: "HU",
  IND: "IN",
  IDN: "ID",
  IRL: "IE",
  ISR: "IL",
  ITA: "IT",
  JPN: "JP",
  MYS: "MY",
  MEX: "MX",
  MON: "MC",
  MAR: "MA",
  NED: "NL",
  NZL: "NZ",
  POL: "PL",
  PRT: "PT",
  QAT: "QA",
  RUS: "RU",
  KSA: "SA",
  SGP: "SG",
  ZAF: "ZA",
  KOR: "KR",
  ESP: "ES",
  SWE: "SE",
  CHE: "CH",
  THA: "TH",
  TUR: "TR",
  UAE: "AE",
  GBR: "GB",
  USA: "US",
  URY: "UY",
  VNM: "VN",
};

export const locationTimezoneMap: { [key: string]: string } = {
  Sakhir: "Asia/Bahrain",
  Jeddah: "Asia/Riyadh",
  Melbourne: "Australia/Melbourne",
  Baku: "Asia/Baku",
  Miami: "America/New_York",
  Monaco: "Europe/Monaco",
  Barcelona: "Europe/Madrid",
  Montréal: "America/Toronto",
  Spielberg: "Europe/Vienna",
  Silverstone: "Europe/London",
  Budapest: "Europe/Budapest",
  "Spa-Francorchamps": "Europe/Brussels",
  Zandvoort: "Europe/Amsterdam",
  Monza: "Europe/Rome",
  "Marina Bay": "Asia/Singapore",
  Suzuka: "Asia/Tokyo",
  Lusail: "Asia/Qatar",
  Austin: "America/Chicago",
  "Mexico City": "America/Mexico_City",
  "São Paulo": "America/Sao_Paulo",
  "Las Vegas": "America/Los_Angeles",
  "Yas Island": "Asia/Dubai",
  Shanghai: "Asia/Shanghai",
  Imola: "Europe/Rome",
};

export const teamNameMap: { [key: string]: string } = {
  Ferrari: "Scuderia Ferrari",
  "Red Bull Racing": "Oracle Red Bull Racing",
  McLaren: "McLaren Formula 1 Team",
  Alpine: "BWT Alpine F1 Team",
  Mercedes: "Mercedes-AMG PETRONAS F1 Team",
  "Aston Martin": "Aston Martin Aramco F1 Team",
  RB: "Visa Cash App RB Formula One Team",
  "Haas F1 Team": "MoneyGram Haas F1 Team",
  Williams: "Williams Racing",
  "Kick Sauber": "Stake F1 Team Kick Sauber",
};
